### PR TITLE
Extract extend codepoints out in seperate array

### PR DESCRIPTION
**Pull request by StefanRvO**
IsCombining() is a hotpath when rendering the screen. Most of the time is spent doing bisearch on the word break interval list to check it characters has the extend property.

Create a seperate table for intervals with the extend property, so they can just be searched in isCombining().

Also some of the intervals in the word break interval list were consecutive and could be combined to reduce the size of the list.

This results in a 25% performance improvement in the benchmark

### CODE REVIEW

**Comment by StefanRvO** [comment]
```
(venv) [stefan@Mjolner:~/FTXUI]$ python ../benchmark/tools/compare.py benchmarks  ./ftxui-benchmark-old ./ftxui-benchmark-new_extend
RUNNING: ./ftxui-benchmark-old --benchmark_out=/tmp/tmp1iok0i1r
2023-07-30T23:44:50+02:00
Running ./ftxui-benchmark-old
Run on (16 X 1700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 4096 KiB (x2)
Load Average: 0.21, 0.78, 1.03
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------------------
Benchmark                      Time             CPU   Iterations
----------------------------------------------------------------
BencharkBasic/0            29374 ns        29306 ns        22691
BencharkBasic/16          723276 ns       721431 ns          959
BencharkBasic/32         1397296 ns      1394385 ns          504
BencharkBasic/48         2111801 ns      2106056 ns          332
BencharkBasic/64         2817181 ns      2802465 ns          249
BencharkBasic/80         3567126 ns      3545261 ns          199
BencharkBasic/96         4246188 ns      4235521 ns          166
BencharkBasic/112        4951427 ns      4939505 ns          142
BencharkBasic/128        5899069 ns      5854523 ns          124
BencharkBasic/144        6487883 ns      6416362 ns          109
BencharkBasic/160        7129990 ns      7093434 ns           98
BencharkBasic/176        7771522 ns      7752767 ns           90
BencharkBasic/192        8499885 ns      8467847 ns           83
BencharkBasic/208        9138172 ns      9117108 ns           77
BencharkBasic/224        9866305 ns      9846852 ns           71
BencharkBasic/240       10525308 ns     10504484 ns           66
BencharkBasic/256       11283726 ns     11262059 ns           62
BencharkText/0          21771740 ns     21729959 ns           32
BencharkText/1          21697059 ns     21655988 ns           32
BencharkText/2          21750964 ns     21709662 ns           32
BencharkText/3          21827933 ns     21786041 ns           32
BencharkText/4          22118184 ns     22069851 ns           32
BencharkText/5          22365184 ns     22321224 ns           31
BencharkText/6          22905485 ns     22855160 ns           31
BencharkText/7          23984292 ns     23936482 ns           29
BencharkText/8          26066434 ns     26014525 ns           27
BencharkText/9          29208648 ns     29159547 ns           24
BencharkText/10         38096980 ns     38016735 ns           18
BenchmarkStyle/1/10       155518 ns       155198 ns         4495
BenchmarkStyle/4/10       384339 ns       383546 ns         1826
BenchmarkStyle/7/10       585576 ns       584240 ns         1185
BenchmarkStyle/10/10      787001 ns       785264 ns          893
BenchmarkStyle/1/30       608395 ns       606645 ns         1149
BenchmarkStyle/4/30       933933 ns       931059 ns          750
BenchmarkStyle/7/30      1216397 ns      1211542 ns          579
BenchmarkStyle/10/30     1512098 ns      1506927 ns          465
BenchmarkStyle/1/50      1462229 ns      1459143 ns          480
BenchmarkStyle/4/50      1877010 ns      1871719 ns          378
BenchmarkStyle/7/50      2298224 ns      2291835 ns          313
BenchmarkStyle/10/50     2661853 ns      2653938 ns          268
BenchmarkStyle/1/70      2732266 ns      2726472 ns          250
BenchmarkStyle/4/70      3226191 ns      3217471 ns          220
BenchmarkStyle/7/70      3682827 ns      3673454 ns          192
BenchmarkStyle/10/70     4067215 ns      4058755 ns          173
BenchmarkStyle/1/90      4385845 ns      4378145 ns          160
BenchmarkStyle/4/90      4923087 ns      4913758 ns          143
BenchmarkStyle/7/90      5433102 ns      5422782 ns          128
BenchmarkStyle/10/90     5984379 ns      5973026 ns          117
BenchmarkStyle/1/110     6466017 ns      6454680 ns          108
BenchmarkStyle/4/110     7066300 ns      7053170 ns           99
BenchmarkStyle/7/110     7654499 ns      7640347 ns           91
BenchmarkStyle/10/110    8243294 ns      8227856 ns           85
BenchmarkStyle/1/130     8952160 ns      8936649 ns           78
BenchmarkStyle/4/130     9608837 ns      9592135 ns           73
BenchmarkStyle/7/130    10268450 ns     10249977 ns           68
BenchmarkStyle/10/130   10904660 ns     10884972 ns           64
BenchmarkStyle/1/150    11849479 ns     11828991 ns           59
BenchmarkStyle/4/150    12559572 ns     12538045 ns           55
BenchmarkStyle/7/150    13280690 ns     13258249 ns           52
BenchmarkStyle/10/150   14034736 ns     14008844 ns           50
BenchmarkStyle/1/170    15142990 ns     15118215 ns           46
BenchmarkStyle/4/170    15953901 ns     15927507 ns           43
BenchmarkStyle/7/170    16785629 ns     16753748 ns           41
BenchmarkStyle/10/170   17540480 ns     17510777 ns           40
BenchmarkStyle/1/190    18870967 ns     18839307 ns           37
BenchmarkStyle/4/190    19775013 ns     19741759 ns           35
BenchmarkStyle/7/190    20593390 ns     20560242 ns           34
BenchmarkStyle/10/190   21472931 ns     21434547 ns           32
RUNNING: ./ftxui-benchmark-new_extend --benchmark_out=/tmp/tmp4982t9a_
2023-07-30T23:45:52+02:00
Running ./ftxui-benchmark-new_extend
Run on (16 X 1700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 4096 KiB (x2)
Load Average: 0.82, 0.85, 1.04
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
----------------------------------------------------------------
Benchmark                      Time             CPU   Iterations
----------------------------------------------------------------
BencharkBasic/0            29829 ns        29781 ns        23423
BencharkBasic/16          517234 ns       516345 ns         1287
BencharkBasic/32          987213 ns       985640 ns          703
BencharkBasic/48         1505388 ns      1501787 ns          466
BencharkBasic/64         2000395 ns      1996066 ns          350
BencharkBasic/80         2501241 ns      2493084 ns          280
BencharkBasic/96         2991614 ns      2985014 ns          235
BencharkBasic/112        3466367 ns      3459231 ns          201
BencharkBasic/128        3987485 ns      3979463 ns          176
BencharkBasic/144        4491234 ns      4482039 ns          156
BencharkBasic/160        4998662 ns      4988155 ns          139
BencharkBasic/176        5487606 ns      5476094 ns          127
BencharkBasic/192        5967862 ns      5955318 ns          117
BencharkBasic/208        6516687 ns      6501894 ns          108
BencharkBasic/224        7003524 ns      6989838 ns          100
BencharkBasic/240        7513712 ns      7497606 ns           93
BencharkBasic/256        8006989 ns      7989211 ns           87
BencharkText/0          15476561 ns     15445865 ns           45
BencharkText/1          15493061 ns     15461396 ns           45
BencharkText/2          15484725 ns     15454149 ns           45
BencharkText/3          15597793 ns     15564999 ns           45
BencharkText/4          15772340 ns     15739121 ns           44
BencharkText/5          15989116 ns     15957382 ns           44
BencharkText/6          16523362 ns     16488883 ns           42
BencharkText/7          17513695 ns     17477315 ns           40
BencharkText/8          19398348 ns     19359372 ns           36
BencharkText/9          22036989 ns     22001112 ns           31
BencharkText/10         30041194 ns     29969892 ns           23
BenchmarkStyle/1/10       126661 ns       126404 ns         5486
BenchmarkStyle/4/10       319662 ns       319007 ns         2196
BenchmarkStyle/7/10       483825 ns       482818 ns         1443
BenchmarkStyle/10/10      655993 ns       654451 ns         1072
BenchmarkStyle/1/30       454051 ns       453117 ns         1543
BenchmarkStyle/4/30       750429 ns       748796 ns          913
BenchmarkStyle/7/30      1000955 ns       998963 ns          691
BenchmarkStyle/10/30     1270890 ns      1268204 ns          547
BenchmarkStyle/1/50      1070177 ns      1067994 ns          652
BenchmarkStyle/4/50      1438295 ns      1435411 ns          484
BenchmarkStyle/7/50      1822290 ns      1818636 ns          386
BenchmarkStyle/10/50     2183572 ns      2178990 ns          317
BenchmarkStyle/1/70      1969443 ns      1965679 ns          347
BenchmarkStyle/4/70      2420631 ns      2415558 ns          290
BenchmarkStyle/7/70      2862684 ns      2856785 ns          246
BenchmarkStyle/10/70     3325158 ns      3318245 ns          212
BenchmarkStyle/1/90      3163868 ns      3157842 ns          221
BenchmarkStyle/4/90      3740333 ns      3733081 ns          188
BenchmarkStyle/7/90      4219127 ns      4211042 ns          168
BenchmarkStyle/10/90     4719243 ns      4710018 ns          148
BenchmarkStyle/1/110     4605183 ns      4596614 ns          152
BenchmarkStyle/4/110     5232103 ns      5222221 ns          135
BenchmarkStyle/7/110     5836750 ns      5825813 ns          120
BenchmarkStyle/10/110    6404707 ns      6392225 ns          110
BenchmarkStyle/1/130     6355221 ns      6343593 ns          108
BenchmarkStyle/4/130     7059885 ns      7047103 ns           99
BenchmarkStyle/7/130     7759877 ns      7745467 ns           90
BenchmarkStyle/10/130    8510229 ns      8494261 ns           83
BenchmarkStyle/1/150     8430237 ns      8415573 ns           83
BenchmarkStyle/4/150     9182555 ns      9165888 ns           76
BenchmarkStyle/7/150     9894941 ns      9877062 ns           71
BenchmarkStyle/10/150   10660677 ns     10641117 ns           65
BenchmarkStyle/1/170    10757501 ns     10736262 ns           65
BenchmarkStyle/4/170    11518043 ns     11497346 ns           61
BenchmarkStyle/7/170    12359239 ns     12333376 ns           56
BenchmarkStyle/10/170   13226250 ns     13201329 ns           53
BenchmarkStyle/1/190    13291791 ns     13267911 ns           53
BenchmarkStyle/4/190    14259141 ns     14231623 ns           49
BenchmarkStyle/7/190    15112828 ns     15083843 ns           46
BenchmarkStyle/10/190   15978815 ns     15950671 ns           44
Comparing ./ftxui-benchmark-old to ./ftxui-benchmark-new_extend
Benchmark                               Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------
BencharkBasic/0                      +0.0155         +0.0162         29374         29829         29306         29781
BencharkBasic/16                     -0.2849         -0.2843        723276        517234        721431        516345
BencharkBasic/32                     -0.2935         -0.2931       1397296        987213       1394385        985640
BencharkBasic/48                     -0.2872         -0.2869       2111801       1505388       2106056       1501787
BencharkBasic/64                     -0.2899         -0.2877       2817181       2000395       2802465       1996066
BencharkBasic/80                     -0.2988         -0.2968       3567126       2501241       3545261       2493084
BencharkBasic/96                     -0.2955         -0.2952       4246188       2991614       4235521       2985014
BencharkBasic/112                    -0.2999         -0.2997       4951427       3466367       4939505       3459231
BencharkBasic/128                    -0.3240         -0.3203       5899069       3987485       5854523       3979463
BencharkBasic/144                    -0.3078         -0.3015       6487883       4491234       6416362       4482039
BencharkBasic/160                    -0.2989         -0.2968       7129990       4998662       7093434       4988155
BencharkBasic/176                    -0.2939         -0.2937       7771522       5487606       7752767       5476094
BencharkBasic/192                    -0.2979         -0.2967       8499885       5967862       8467847       5955318
BencharkBasic/208                    -0.2869         -0.2868       9138172       6516687       9117108       6501894
BencharkBasic/224                    -0.2902         -0.2901       9866305       7003524       9846852       6989838
BencharkBasic/240                    -0.2861         -0.2862      10525308       7513712      10504484       7497606
BencharkBasic/256                    -0.2904         -0.2906      11283726       8006989      11262059       7989211
BencharkText/0                       -0.2891         -0.2892      21771740      15476561      21729959      15445865
BencharkText/1                       -0.2859         -0.2860      21697059      15493061      21655988      15461396
BencharkText/2                       -0.2881         -0.2881      21750964      15484725      21709662      15454149
BencharkText/3                       -0.2854         -0.2856      21827933      15597793      21786041      15564999
BencharkText/4                       -0.2869         -0.2868      22118184      15772340      22069851      15739121
BencharkText/5                       -0.2851         -0.2851      22365184      15989116      22321224      15957382
BencharkText/6                       -0.2786         -0.2785      22905485      16523362      22855160      16488883
BencharkText/7                       -0.2698         -0.2698      23984292      17513695      23936482      17477315
BencharkText/8                       -0.2558         -0.2558      26066434      19398348      26014525      19359372
BencharkText/9                       -0.2455         -0.2455      29208648      22036989      29159547      22001112
BencharkText/10                      -0.2115         -0.2117      38096980      30041194      38016735      29969892
BenchmarkStyle/1/10                  -0.1856         -0.1855        155518        126661        155198        126404
BenchmarkStyle/4/10                  -0.1683         -0.1683        384339        319662        383546        319007
BenchmarkStyle/7/10                  -0.1738         -0.1736        585576        483825        584240        482818
BenchmarkStyle/10/10                 -0.1665         -0.1666        787001        655993        785264        654451
BenchmarkStyle/1/30                  -0.2537         -0.2531        608395        454051        606645        453117
BenchmarkStyle/4/30                  -0.1965         -0.1958        933933        750429        931059        748796
BenchmarkStyle/7/30                  -0.1771         -0.1755       1216397       1000955       1211542        998963
BenchmarkStyle/10/30                 -0.1595         -0.1584       1512098       1270890       1506927       1268204
BenchmarkStyle/1/50                  -0.2681         -0.2681       1462229       1070177       1459143       1067994
BenchmarkStyle/4/50                  -0.2337         -0.2331       1877010       1438295       1871719       1435411
BenchmarkStyle/7/50                  -0.2071         -0.2065       2298224       1822290       2291835       1818636
BenchmarkStyle/10/50                 -0.1797         -0.1790       2661853       2183572       2653938       2178990
BenchmarkStyle/1/70                  -0.2792         -0.2790       2732266       1969443       2726472       1965679
BenchmarkStyle/4/70                  -0.2497         -0.2492       3226191       2420631       3217471       2415558
BenchmarkStyle/7/70                  -0.2227         -0.2223       3682827       2862684       3673454       2856785
BenchmarkStyle/10/70                 -0.1824         -0.1824       4067215       3325158       4058755       3318245
BenchmarkStyle/1/90                  -0.2786         -0.2787       4385845       3163868       4378145       3157842
BenchmarkStyle/4/90                  -0.2402         -0.2403       4923087       3740333       4913758       3733081
BenchmarkStyle/7/90                  -0.2234         -0.2235       5433102       4219127       5422782       4211042
BenchmarkStyle/10/90                 -0.2114         -0.2115       5984379       4719243       5973026       4710018
BenchmarkStyle/1/110                 -0.2878         -0.2879       6466017       4605183       6454680       4596614
BenchmarkStyle/4/110                 -0.2596         -0.2596       7066300       5232103       7053170       5222221
BenchmarkStyle/7/110                 -0.2375         -0.2375       7654499       5836750       7640347       5825813
BenchmarkStyle/10/110                -0.2230         -0.2231       8243294       6404707       8227856       6392225
BenchmarkStyle/1/130                 -0.2901         -0.2902       8952160       6355221       8936649       6343593
BenchmarkStyle/4/130                 -0.2653         -0.2653       9608837       7059885       9592135       7047103
BenchmarkStyle/7/130                 -0.2443         -0.2443      10268450       7759877      10249977       7745467
BenchmarkStyle/10/130                -0.2196         -0.2196      10904660       8510229      10884972       8494261
BenchmarkStyle/1/150                 -0.2886         -0.2886      11849479       8430237      11828991       8415573
BenchmarkStyle/4/150                 -0.2689         -0.2690      12559572       9182555      12538045       9165888
BenchmarkStyle/7/150                 -0.2549         -0.2550      13280690       9894941      13258249       9877062
BenchmarkStyle/10/150                -0.2404         -0.2404      14034736      10660677      14008844      10641117
BenchmarkStyle/1/170                 -0.2896         -0.2898      15142990      10757501      15118215      10736262
BenchmarkStyle/4/170                 -0.2780         -0.2781      15953901      11518043      15927507      11497346
BenchmarkStyle/7/170                 -0.2637         -0.2638      16785629      12359239      16753748      12333376
BenchmarkStyle/10/170                -0.2460         -0.2461      17540480      13226250      17510777      13201329
BenchmarkStyle/1/190                 -0.2956         -0.2957      18870967      13291791      18839307      13267911
BenchmarkStyle/4/190                 -0.2789         -0.2791      19775013      14259141      19741759      14231623
BenchmarkStyle/7/190                 -0.2661         -0.2664      20593390      15112828      20560242      15083843
BenchmarkStyle/10/190                -0.2559         -0.2558      21472931      15978815      21434547      15950671
OVERALL_GEOMEAN                      -0.2546         -0.2543             0             0             0             0
```

**Comment by StefanRvO** [comment]
Hmm, some tests seems to be failing, will look into it later.

**Comment by StefanRvO** [comment]
Fixed the issue, had set all the stop values to start... But now i only see 3% improvement in the benchmark :/

```
BencharkBasic/0                      -0.0057         -0.0073         29629         29459         29570         29355
BencharkBasic/16                     +0.0284         +0.0273        721569        742061        720057        739748
BencharkBasic/32                     +0.0207         +0.0196       1406370       1435471       1403587       1431059
BencharkBasic/48                     -0.0016         -0.0031       2131310       2127857       2125661       2118972
BencharkBasic/64                     +0.0370         +0.0357       2857310       2962898       2850002       2951859
BencharkBasic/80                     +0.0124         +0.0104       3575213       3619660       3566476       3603438
BencharkBasic/96                     +0.0394         +0.0372       4298808       4468117       4287959       4447501
BencharkBasic/112                    +0.0070         +0.0049       5009160       5044460       4997736       5022308
BencharkBasic/128                    +0.0496         +0.0475       5749467       6034451       5735843       6008450
BencharkBasic/144                    -0.0233         -0.0242       6476773       6325623       6461565       6305056
BencharkBasic/160                    +0.0391         +0.0373       7186810       7467873       7169650       7437213
BencharkBasic/176                    -0.0056         -0.0065       7892599       7848754       7873416       7822383
BencharkBasic/192                    -0.0086         -0.0095       8626380       8552095       8605966       8523844
BencharkBasic/208                    -0.0115         -0.0124       9376202       9268148       9353231       9237571
BencharkBasic/224                    -0.0075         -0.0088      10049332       9974237      10026217       9937882
BencharkBasic/240                    -0.0180         -0.0190      10780300      10585984      10754221      10549804
BencharkBasic/256                    -0.0216         -0.0223      11438532      11191349      11412559      11158627
BencharkText/0                       -0.0273         -0.0280      22425386      21814038      22374620      21747345
BencharkText/1                       -0.0196         -0.0203      22442950      22002880      22389140      21935658
BencharkText/2                       -0.0253         -0.0260      22394754      21827684      22343150      21762663
BencharkText/3                       -0.0219         -0.0225      22424896      21934562      22372762      21869056
BencharkText/4                       -0.0267         -0.0274      22660608      22054938      22606782      21988193
BencharkText/5                       -0.0275         -0.0284      22899195      22268462      22846546      22198175
BencharkText/6                       -0.0243         -0.0252      23470288      22900719      23416885      22827623
BencharkText/7                       -0.0255         -0.0261      24498662      23873474      24441195      23802990
BencharkText/8                       -0.0260         -0.0267      26557689      25867185      26498479      25790991
BencharkText/9                       -0.0277         -0.0279      29732795      28909239      29650857      28823597
BencharkText/10                      -0.0618         -0.0604      39777469      37320953      39596997      37204209
BenchmarkStyle/1/10                  -0.0433         -0.0431        156641        149858        156186        149461
BenchmarkStyle/4/10                  -0.0555         -0.0551        391531        369782        390265        368761
BenchmarkStyle/7/10                  -0.0418         -0.0418        588509        563891        586787        562265
BenchmarkStyle/10/10                 -0.0443         -0.0440        789598        754581        787069        752458
BenchmarkStyle/1/30                  -0.0459         -0.0458        624647        595991        622920        594380
BenchmarkStyle/4/30                  -0.0452         -0.0444        946997        904222        943568        901672
BenchmarkStyle/7/30                  -0.0417         -0.0417       1225607       1174551       1222134       1171172
BenchmarkStyle/10/30                 -0.0707         -0.0697       1564770       1454132       1558357       1449783
BenchmarkStyle/1/50                  -0.0315         -0.0319       1498510       1451313       1494838       1447106
BenchmarkStyle/4/50                  -0.0320         -0.0325       1890715       1830201       1885984       1824703
BenchmarkStyle/7/50                  -0.0837         -0.0828       2396625       2196024       2385397       2187921
BenchmarkStyle/10/50                 -0.0357         -0.0371       2656956       2562110       2650394       2551960
BenchmarkStyle/1/70                  -0.0320         -0.0320       2789224       2700097       2783041       2693964
BenchmarkStyle/4/70                  -0.0493         -0.0489       3311147       3147937       3301828       3140359
BenchmarkStyle/7/70                  -0.0334         -0.0333       3704106       3580245       3694924       3571796
BenchmarkStyle/10/70                 -0.0509         -0.0502       4216706       4001922       4204102       3992857
BenchmarkStyle/1/90                  -0.0373         -0.0369       4547422       4377688       4535462       4367972
BenchmarkStyle/4/90                  -0.0412         -0.0402       5085759       4876122       5068650       4864817
BenchmarkStyle/7/90                  -0.0504         -0.0494       5646100       5361449       5627449       5349562
BenchmarkStyle/10/90                 -0.0963         -0.0942       6512462       5885132       6482830       5871899
BenchmarkStyle/1/110                 -0.0434         -0.0420       6712162       6420893       6689060       6407861
BenchmarkStyle/4/110                 -0.0466         -0.0457       7327183       6985459       7304184       6970612
BenchmarkStyle/7/110                 -0.0515         -0.0501       7974622       7564107       7945734       7548026
BenchmarkStyle/10/110                -0.0553         -0.0516       8584726       8109940       8531625       8091775
BenchmarkStyle/1/130                 -0.0491         -0.0441       9360165       8900460       9292186       8882117
BenchmarkStyle/4/130                 -0.0674         -0.0654      10215029       9526661      10172272       9507413
BenchmarkStyle/7/130                 -0.0397         -0.0389      10563172      10144036      10532508      10122834
BenchmarkStyle/10/130                -0.0358         -0.0345      11189086      10788386      11150567      10766174
BenchmarkStyle/1/150                 -0.0356         -0.0353      12209832      11775671      12181129      11751532
BenchmarkStyle/4/150                 -0.0444         -0.0429      13049143      12470019      13002624      12445160
BenchmarkStyle/7/150                 -0.0375         -0.0372      13669537      13156962      13638410      13130446
BenchmarkStyle/10/150                -0.0363         -0.0360      14357744      13836816      14325002      13808683
BenchmarkStyle/1/170                 -0.0336         -0.0334      15585851      15062731      15551830      15032094
BenchmarkStyle/4/170                 -0.0335         -0.0333      16360946      15812966      16326466      15782127
BenchmarkStyle/7/170                 -0.0340         -0.0339      17161674      16577600      17124426      16543174
BenchmarkStyle/10/170                -0.0384         -0.0381      18021697      17330513      17979866      17294007
BenchmarkStyle/1/190                 -0.0336         -0.0335      19409450      18757134      19366523      18718131
BenchmarkStyle/4/190                 -0.0368         -0.0366      20291833      19545060      20247787      19507299
BenchmarkStyle/7/190                 -0.0423         -0.0410      21284350      20384656      21215155      20344674
BenchmarkStyle/10/190                -0.0661         -0.0653      22711606      21211403      22647011      21167623
OVERALL_GEOMEAN                      -0.0299         -0.0299             0             0             0             0
```

**Comment by StefanRvO** [comment]
Also, https://github.com/StefanRvO/FTXUI/commit/fe34672538bdd78a2c3577e40df79fa0cc520b27 gives a slightly bigger performance improvement, but uses a big lookup table, so higher RAM consumption. I'm not sure what we rather want @ArthurSonzogni , I'm leaning toward the smaller table to keep the RAM usage low.

**Comment by clement-roblot** [comment]
@StefanRvO Amazin! Yes that is what I had in mind in #705. I'm impressed by the 25% speed improvement, especially with my next question.

You have merged all the contiguous blocks in the table, but this table got holes. When we fall in one of those holes we keep the default interval of `WBP::ALetter` (if I read the code well). That means you could push your system further by merging the parts of the table that are returning `WBP::ALetter` even when there is a hole between those parts.

My explanation isn´t clear, here is an example:

Screenshot from 2023-07-31 13-49-35

If we search for the character:
- 0x00A8D : WBP::ALetter (because it's in the range)
- 0x00A8E : WBP::ALetter (because it is out of any range)
- 0x00A8F :  WBP::ALetter (because it's in the following range)

In other word this block of ranges could be merged into 1:  `{0x00A85, 0x00AB9, WBP::ALetter},`. This change could make this table go from 993 to 648 cells.

But wait! There is more!

As we are already using `WBP::ALetter` when we fall outside of any ranges in the table. Why not simply remove all the explicit ranges that specify `WBP::ALetter`. That way this table only specifies the ranges with special intervals, anything else is `WBP::ALetter`.

[Some testing happening]

Ok, turns out my last idea is a bad one. I went from an improovement of 41% with your changes (not sure why we get such different results, but I'm fine with bigger numbers here ^^), to 37% with what I suggest (removing all the `WBP::ALetter` ranges)... So apparently this doesn´t help :sweat_smile: 

But I don't see how extending and merging the `WBP::ALetter` to cover holes between them wouldn´t make things better regarding memory and lookup times.

**Comment by clement-roblot** [comment]
Actually I just realized that the change I suggest can be pushed even further. In the example I gave (with the image), a better replacement range would be: `{0x00A84, 0x00ABB, WBP::ALetter},`. That way we really take all the holes in between, but also before and after the range.

**Comment by clement-roblot** [comment]
@StefanRvO I updated your python script with what I described here: https://pastebin.com/FqPv8vGG
(I'm currently testing if that makes things better)

**Comment by clement-roblot** [comment]
I don´t understand why, but what I suggest makes the benchmark 1% to 2% worse. I pushed my tests on this branch: https://github.com/clement-roblot/FTXUI/tree/improve_iscombining_performance

**Comment by StefanRvO** [comment]
Yeah, i agree that it should be possible to remove the ALetter ranges and just default to that if no intervals are found, but i don't see any performance improvements either when doing that. By far the biggest improvement came from splitting out the extend ranges in there own table. Shrinking the big table itself gave almost no improvements. So i don't think we should focus too much on shrinking the table further, it doesn't seem to make a difference.

I will tidy up the changes a bit to avoid hardcoding the g_extend_characters, and then i think this should be good to merge. After that, we can maybe try profiling again and see if there are other bottlenecks that would be more economic to address?

**Comment by ArthurSonzogni** [comment]
Awesome! Thank you! I am impressed by the performance improvement.

I would be happy if there wasn't a second table. Maybe we could precompute the second from the first at startup. I will give it a try when I get more time, and check if can retain the performance improvement.

**Comment by StefanRvO** [comment]
@ArthurSonzogni I got it to construct the table at compile time in my new commit. Not exactly the most readable code, but it does work.

**Comment by ArthurSonzogni** [comment]
Perfect! Thank you very much!

**Pull request merged**
