### PR TITLE
[Feature]  "Suspend" and "Resume" the screen

### PR DESCRIPTION
**Pull request by vnepogodin**
🚧 suspend FTXUI on interactive actions such as "bash" shell

Resolves: https://github.com/ArthurSonzogni/FTXUI/issues/301

### CODE REVIEW

**Comment by vnepogodin** [comment]
so I did resolve error from Windows CI
Which was related to c++20 feature:
member initializer list.
https://en.cppreference.com/w/cpp/language/constructor

**Comment by ArthurSonzogni** [comment]
Thanks!
Just a quick note: I am a bit busy at the moment. I will try to take a look very soon.

**Comment by ArthurSonzogni** [comment]
Thanks! I took a look. I applied the following changes:
- Simplify the example. Keep only the essential. Goal is to keep examples short to favorise developers to read them.
- Instead of exposing Suspend() / Resume(), I preferred exposing a callback decorator. This ensures for every "Uninstall()", there is a matching "Install()" called.
- Remove the parts about clearing the screen. I was not really understanding its purpose and doesn't look correct clearing the screen after uninstalling it. I was not sure the command was correct. Developers can anyway clear the screen themselves if they want. I prefer letting them the choice.

Does it looks good to you?

**Comment by vnepogodin** [comment]
Yeah looks good. I'm ok with callback function instead of exposing already existed.
Example looks good too. It's simple though as it should be

I was clearing screen because then I run`bash`(for example) and drag mouse it starts outputting weird characters (you can confirm that from example I created later on)

**Comment by ArthurSonzogni** [comment]
> I was clearing screen because then I runbash(for example) and drag my mouse it starts outputting weird characters to stdout stream(you can confirm that from example I created later on)

Good observation. We were forgetting to call std::flush in order to commit the new state before proceeding further. This has now been fixed by the latest patch.

**Pull request merged**
