### PR TITLE
Feature: ResizableSplit with custom separator

### PR DESCRIPTION
**Pull request by pllee4**
This resolves:
    https://github.com/ArthurSonzogni/FTXUI/issues/580

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Thanks! This is grealy appreciated!
I like it. I wonder if there are other ways to make it customizable easily.

I think I will take your patch, but modify the interface to allow more.

**Comment by ArthurSonzogni** [comment]
I wasn't able to push my change toward this branch:
```
ERROR: Permission to pllee4-Experimental/FTXUI.git denied to ArthurSonzogni.
```
I guess you opted-in for not giving me write access to the branch?
I will have to upload my branch and open a separate PR.

**Comment by pllee4** [comment]
@ArthurSonzogni sorry about the access issue, I have granted you the access if case you need it.

**Comment by ArthurSonzogni** [comment]
>  @ArthurSonzogni sorry about the access issue, I have granted you the access if case you need it.

Thanks! I am not quite sure this was about you. If you did nothing, by default it should grant me the right to push on your branch.
So, if you did nothing special, then the problem was likely on my side ;-)

**Comment by pllee4** [comment]
> > @ArthurSonzogni sorry about the access issue, I have granted you the access if case you need it.
> 
> Thanks! I am not quite sure this was about you. If you did nothing, by default it should grant me the right to push on your branch. So, if you did nothing special, then the problem was likely on my side ;-)

No worries, I guess the issue was on my side. Perhaps it was because I forked the repo to an organization.

**Pull request closed without merging**
