### PR TITLE
Ip input component

### PR DESCRIPTION
**Pull request by mingsheng13**
I wrote a component for inputting IPV4 address. One bug that I wasn't able to fix is when using cursor to remove the dots it breaks the logic. I think the only way to fix this is to be able to get the cursor_position() outside the Input component.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Thanks @mingsheng13 !

As as said in: https://github.com/ArthurSonzogni/FTXUI/issues/672
I believe an IpInput component to be too specific for FTXUI. If you made a repository, I could contribute to make the CMake config usable for others and reference it from:
https://github.com/ArthurSonzogni/FTXUI#libraries-for-ftxui
?

I really would like folks to add their own set of components, maybe this could be the first one?

**Comment by mingsheng13** [comment]
> As as said in: #672 I believe an IpInput component to be too specific for FTXUI. If you made a repository, I could contribute to make the CMake config usable for others and reference it from: https://github.com/ArthurSonzogni/FTXUI#libraries-for-ftxui ?


Thank you for the reply. That's actually what I wanted to do! I'll make it in my repo.

**Comment by mingsheng13** [comment]
I've moved it to here. https://github.com/mingsheng13/ip-input-ftxui . Please tell me if I'm doing anything wrong. Thanks :)

**Comment by ArthurSonzogni** [comment]
Awesome!

I [forked your repository](https://github.com/ArthurSonzogni/ftxui-ip-input) and improved it. I will work on it for a few days and submit PR against your repository when I am done.

**Comment by mingsheng13** [comment]
Thanks! I had a look at the fork and was impressed by the code quality. Wish I could be as good as you 😭

**Comment by ArthurSonzogni** [comment]
Thanks!

I added `ftxui-ip-input` in the FTXUI README.

**Pull request closed without merging**
