### PR TITLE
Feature: `hyperlink` support.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
See the [OSC 8 page](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). FTXUI support proposed by @aaleino in [#662](https://github.com/ArthurSonzogni/FTXUI/issues/662).

API:
```cpp
auto link = text("Click here") | hyperlink("https://github.com/FTXUI")
```

Fixed:https://github.com/ArthurSonzogni/FTXUI/issues/662

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Hello @aaleino, Could you please take a look?

This stores the hyperlink string into every cells. Most likely with string optimization, this shouldn't translate into using too much memory when not used.

I ran a benchmark. This makes FTXUI screen rendering 50% slower. On my laptop, on a 128x128  We go from 15'000fps to 7'500fps on a 80x80 grid.

There are still plenty of room for other work. It might be fine. We might also find ways to improve it over time. We could store the string separately and store only its index.

<details>

### Benchmark (after)
```raw
------------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BencharkBasic/0          608 ns          608 ns      1160480
BencharkBasic/16        8874 ns         8874 ns        78888
BencharkBasic/32       28301 ns        28301 ns        24764
BencharkBasic/48       50201 ns        50201 ns        14035
BencharkBasic/64       71435 ns        71432 ns         9745
BencharkBasic/80       92506 ns        92505 ns         7588
BencharkBasic/96      113480 ns       113476 ns         6145
BencharkBasic/112     135262 ns       135256 ns         5189
BencharkBasic/128     155677 ns       155674 ns         4492
BencharkBasic/144     175585 ns       175579 ns         3983
BencharkBasic/160     198503 ns       198499 ns         3560
BencharkBasic/176     225427 ns       225413 ns         3106
BencharkBasic/192     247805 ns       247793 ns         2832
BencharkBasic/208     268403 ns       268394 ns         2606
BencharkBasic/224     291348 ns       291339 ns         2407
BencharkBasic/240     312722 ns       312713 ns         2233
BencharkBasic/256     335078 ns       335071 ns         2089
```

### Benchmark (before)
```
------------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BencharkBasic/0          598 ns          597 ns      1173144
BencharkBasic/16        5207 ns         5204 ns       134531
BencharkBasic/32        9157 ns         9151 ns        76168
BencharkBasic/48       22434 ns        22434 ns        31155
BencharkBasic/64       34216 ns        34216 ns        20463
BencharkBasic/80       46032 ns        46032 ns        15227
BencharkBasic/96       57430 ns        57428 ns        12120
BencharkBasic/112      69377 ns        69376 ns        10075
BencharkBasic/128      80807 ns        80805 ns         8685
BencharkBasic/144      93443 ns        93366 ns         7508
BencharkBasic/160     103344 ns       103342 ns         6786
BencharkBasic/176     115534 ns       115533 ns         6042
BencharkBasic/192     126967 ns       126964 ns         5523
BencharkBasic/208     138934 ns       138932 ns         5056
BencharkBasic/224     149849 ns       149844 ns         4682
BencharkBasic/240     160696 ns       160693 ns         4346
BencharkBasic/256     172293 ns       172287 ns         4066
```

</details>

**Comment by ArthurSonzogni** [comment]
In the latest patchset, I am now storing a `uint8_t` per Pixel/Cell. Then the `Screen` is registering up to 254 hyperlink. This improved performance by 2x and we are now back to the same level of performance.

**Comment by aaleino** [comment]
Thanks a a lot, that was fast! It has been awhile since I used FTXUI, but i tried it with by modifying the example modal_dialog.cpp:

```
// Definition of the modal component. The details are not important.
Component ModalComponent(std::function<void()> do_nothing,
                         std::function<void()> hide_modal) {
  auto component = Container::Vertical({
      Button("Do nothing", do_nothing, button_style),
      Button("Quit modal", hide_modal, button_style),
  });
  // Polish how the two buttons are rendered:
  component |= Renderer([&](Element inner) {
    return vbox({
               text("Modal component ") | hyperlink("http://www.google.com"),
               separator(),
               inner,
           })                               //
           | size(WIDTH, GREATER_THAN, 30)  //
           | border;                        //
  });
  return component;
}
``` 

It compiled but the hyperlink does not show? Is the test incorrect?

**Comment by ArthurSonzogni** [comment]
> It compiled but the hyperlink does not show? Is the test incorrect?

It seems to work. Here is what I get with your example:

https://github.com/ArthurSonzogni/FTXUI/assets/4759106/0808a375-3bc4-4627-9cc9-cdbed46ddf30


My terminal emulator `kitty` only display some curly underline when the mouse is over it. You migth want to add some `| color(Color::Blue) | bold` to highlight the link?

**Comment by aaleino** [comment]
Ah, my mistake, I was running the example under tmux which had apparently captured the escape code. Running in windows terminal without tmux worked fine. 

Then I think it works intuitively and I will definitely use this feature. I will start to incorporate this into my source code.

Thank you very much!

**Pull request merged**
