### PR TITLE
Use globally set CMAKE_CXX_STANDARD, if it is set

### PR DESCRIPTION
**Pull request by lefticus**
This makes FTXUI a better citizen for things like CPM, so that you can have consistent c++ standards settings across your dependencies.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Thanks!

What are the benefits of having a consistent c++ standard across all the dependencies?

The cons: some users won't be able to depend on FTXUI if they specify a standard lower than c++17

**Comment by lefticus** [comment]
Compiling with different standards can lead to ODR violations. I discovered
a particular issue while compiling my code with 20 and ftxui with 17 while
upgrading my Best Practices template repository.

Someone could still choose to risk a 14/17 combination with ftxui, they
would just need to set the CXX_STANDARD immediately before consuming your
CMakeLists, and restore it immediately after (I have done this in other
projects by making use of sub folders)

I have confirmed that other projects (like spdlog) behave similarly to what
I've proposed for yours.

We could add a check to make sure the standard is at least 17, and bump it
to 17 if it is not? But I must say that some of these subtle issues around
things like ODR violations are concerning me more and more as we talk about
the security of C++.

**Comment by ArthurSonzogni** [comment]
Thanks for the explanation!

We might want to tweak it a bit in the future, but the current patches sounds good to me. Thanks for making it!

**Comment by SpaceIm** [comment]
The proper fix should be to add `target_compile_options(${library} PUBLIC cxx_std_17)` and remove all references to `CMAKE_CXX_STANDARD`.
https://github.com/ArthurSonzogni/FTXUI/pull/156 got it right, but https://github.com/ArthurSonzogni/FTXUI/pull/552 broke it and afterwards it was a succession of incorrect workarounds.

**Pull request merged**
