### PR TITLE
Improved Introductory Tutorial Page

### PR DESCRIPTION
**Pull request by Hunter-Zolomon**
This PR solves #434 by improving on the existing introductory tutorial through adjustment of the grammar and vocabulary of the sentences, rewriting of sentences, writing new descriptions for sub-headings, and adding new link references for the corresponding discussion elements. 

I have not replaced the inline script ascii calls yet, and there might be a few other things that might require some adjustment. However, this version looks much cleaner, consistent, and descriptive that the previous iteration.

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Thanks! That is really appreciated.
I will take a look in details tonight or tomorrow.

**Comment by ArthurSonzogni** [comment]
Thanks!

This is a markdown file used to generate:
https://arthursonzogni.github.io/FTXUI/
using doxygen.

If I apply your patch, but everything looks broken. The main page is blank. After a few fixes like adding back the `\mainpage` command I can see it rendered. However many links are now broken.

I can't apply this patch as is. However it contains many improvement of the English speaking. It will take me some time to cherry-pick every interesting parts.

**Comment by Hunter-Zolomon** [comment]
Apologies. I was reviewing the document on github and optimized the markdown file based on proper .md formatting. I completely forgot that this file was also being compiled by doxygen to be displayed on the documentation page. This is due to the fact that the "Build using CMake" reference in the github main page is still referencing the github document instead of the documentation, creating some confusion.

I am assuming that the content referencing is probably broken, including some visual formatting, however, I believe the link references should still work without issue. I can update the markdown file to support the doxygen file instead. Based on this, I will also update the main page and remove that link.

**Comment by ArthurSonzogni** [comment]
Thanks for your contribution!

**Comment by Hunter-Zolomon** [comment]
You're welcome!

I see that you have committed the suggested syntax changes yourself. I will take a look at the built doxygen result once you push it to the main branch. Additionally, the other PR should fix the incorrect README CMake build link reference.

**Comment by ArthurSonzogni** [comment]
I also modified the workflow so that a new documentation for every commit. Previously, it was for every new version.
https://github.com/ArthurSonzogni/FTXUI/commit/f80e20c4aa83797ceec103e1d4ba08351b4e035e

The bot hasn't yet finished. We will see.

**Pull request merged**
